#!/usr/bin/env bash

set -e

get_mysql_status()
{
    if [[ $(command -v mysql.server) ]]; then
        mysql_status=$(mysql.server status)
        regex="running \(([0-9]+)\)"
        if [[ $mysql_status =~ $regex ]]; then
            mysql_pid=${BASH_REMATCH[1]}
            echo "[MySQL]"
        fi
    fi
    
}

get_postgresql_status()
{
    if [[ $(command -v pg_ctl) ]]; then
        if [[ -z "$PGDATA" ]]; then
            postgresql_status=$(pg_ctl status -D /usr/local/var/postgres)
        else
            postgresql_status=$(pg_ctl status)
        fi
        regex="running \(PID: ([0-9]+)\)"
        if [[ $postgresql_status =~ $regex ]]; then
            postgresql_pid=${BASH_REMATCH[1]}
            echo "[PG]"
        fi
    fi
}

if [[ $(uname) == "Darwin" ]]; then
    mysql_status=$(get_mysql_status)
    postgresql_status=$(get_postgresql_status)
    echo "${mysql_status}${postgresql_status}"
fi
