#!/usr/bin/env bash

# Created by Uğur "vigo" Özyılmazel,
# feel free to add/change or implement more kool features
# @vigobronx

out=()
case $(uname) in
    "Darwin" )
        iface_data=$(ifconfig -lu);;
esac

for iface in $iface_data; do
    ip_address=$(ifconfig $iface | grep --colour=never -oe 'inet [[:digit:]]*.[[:digit:]]*.[[:digit:]]*.[[:digit:]]*' | cut -f2 -d' ')
    if [[ $ip_address && ! $iface == "lo0" ]]; then
        iface_and_ip=$(printf ",%s:%s" "${iface}" "${ip_address}")
        out+="${iface_and_ip}"
    fi
done
if [[ $out ]]; then
    printf "[%s]" "${out:1}"
else
    printf "[\xE2\x8C\x81]"
fi

