#!/usr/bin/env bash

# Created by Uğur "vigo" Özyılmazel,
# feel free to add/change or implement more kool features
# @vigobronx

output=()
case $(uname) in
    "Darwin" )
        interface_list=$(ifconfig -lu)
    ;;
    "Linux" )
        lines=$(ifconfig -s | wc -l)
        interface_list=$(ifconfig -s | tail -n $(( $lines-1 )) | cut -f1 -d' ' | xargs)
    ;;
esac

for iface in $interface_list; do
    ip_address=$(ifconfig $iface | grep --colour=never -oe 'inet [0-9.]\+' | cut -f2 -d' ')
    if [[ $ip_address && $ip_address != "127.0.0.1" ]]; then
        iface_and_ip=$(printf ",%s:%s" "${iface}" "${ip_address}")
        output+="${iface_and_ip}"
    fi
done

if [[ $output ]]; then
    printf "[%s]" "${output:1}"
else
    printf "[\xE2\x8C\x81]"
fi
