#!/usr/bin/env bash

# Created by Uğur "vigo" Özyılmazel,
# feel free to add/change or implement more kool features
# @vigobronx

output=()
case $(uname) in
    "Darwin" )
        interface_list=$(ifconfig -lu)
        for iface in $interface_list; do
            ip_address=$(ipconfig getifaddr $iface)
            if [[ $ip_address ]]; then
                iface_and_ip=$(printf ",%s:%s" "${iface}" "${ip_address}")
                output+="${iface_and_ip}"
            fi
        done
        ;;
    "Linux" )
        if [[ ! $WE_ARE_ON_GENTOO ]]; then
            ip_address=$(hostname -I | cut -f1 -d' ')
            output=(",${ip_address}")
        fi
        ;;
esac

if [[ $output ]]; then
    printf "[%s]" "${output:1}"
else
    printf "[\xE2\x8C\x81]"
fi
