#!/usr/bin/env bash

set -e


if [[ `uname` == "Darwin" ]]; then
    # requires mysql which is installed from brew
    # brew install mysql :)
    if [[ `mysql.server` ]]; then
        # SUCCESS! MySQL running (52953)
        mysql_status=`mysql.server status`
        regex="running \(([0-9]+)"
        if [[ $mysql_status =~ $regex ]]; then
            mysql_pid=$BASH_REMATCH[1]
            echo "MySQL "
        fi
    fi
fi

