#!/usr/bin/env bash

if [[ `which rbenv` ]]; then
    rbenv_version=`rbenv version-name`
    if [[ $rbenv_version != "system" && ! -z $rbenv_version ]]; then
        echo "[${rbenv_version}]"
    fi
fi
