# non interactive shell
[ -z "$PS1" ] && return

export DOTFILES_PATH="$HOME/Dotfiles"

source $DOTFILES_PATH/shell/env
source $DOTFILES_PATH/shell/alias
source $DOTFILES_PATH/shell/ls_colors

# Load private files
# ----------------------------------------------------------------------------
# Loads every file under private/ folder!
if [[ -d $DOTFILES_PATH/private ]]; then
    if [ "$(ls -A $DOTFILES_PATH/private)" ]; then
        for file in $DOTFILES_PATH/private/*; do
            source $file
        done
    fi
fi
# ----------------------------------------------------------------------------


# Are we on Mac ?
# ----------------------------------------------------------------------------
if [[ `uname` == "Darwin" ]]; then
    # sw_vers -productVersion => 10.10
    source $DOTFILES_PATH/shell/mac_specific
fi
# ----------------------------------------------------------------------------


# Are we on Ubuntu
# ----------------------------------------------------------------------------
if [[ `which lsb_release` ]]; then
    if [[ `lsb_release -i | awk '{print $3}'` == "Ubuntu" ]]; then
        source $DOTFILES_PATH/shell/ubuntu_specific
    fi
fi
# ----------------------------------------------------------------------------


# Do we have rbenv ?
# ----------------------------------------------------------------------------
if [[ -d $HOME/.rbenv ]]; then
    export PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
fi
# ----------------------------------------------------------------------------


# Bash Completions
# ----------------------------------------------------------------------------

# Load completion files
for completion_file in $DOTFILES_PATH/completions/*; do
    source $completion_file
done

# Do we have pip?
if [[ `which pip` ]]; then
    eval "`pip completion --bash`"
fi
# ----------------------------------------------------------------------------

# Load Functions
source $DOTFILES_PATH/shell/functions